name: Deploy website on push

on:
  push:
    branches:
      - production

jobs:
  web-deploy:
    name: Deploy
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Get Lates code
      uses: actions/checkout@v3
      
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.psbyhom.com
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        server-dir: psbyhom.com/public_html/
